sudo: required
cache:
  directories:
    - $HOME/.m2
language: clojure
jdk:
  - oraclejdk8
before_script:
  - echo 'Europe/Helsinki' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
script: lein do clean, deps, compile, uberjar
before_deploy:
before_deploy:
  - mkdir s3-deploy
  - ln target/kite-notifier-0.1.0-SNAPSHOT-standalone.jar "s3-deploy/kite-notifier-travis-${TRAVIS_BRANCH}.jar"	 
deploy:
  provider: s3
  region: eu-central-1
  skip_cleanup: true
  bucket: "kite-notifier-lambda-build"
  acl: public_read
  local_dir: s3-deploy
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
