sudo: required
cache:
  directories:
    - $HOME/.m2
language: clojure
jdk:
  - oraclejdk8
before_script:
  - echo 'Europe/Helsinki' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
script: lein do clean, deps, compile, uberjar
deploy:
  provider: s3
  region: eu-central-1
  skip_cleanup: true
  bucket: "kite-notifier-lambda-build"
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  acl: public_read
  local_dir: s3-deploy
