sudo: required
cache:
  directories:
    - $HOME/.m2
language: clojure
jdk:
  - oraclejdk8
before_script:
  - echo 'Europe/Helsinki' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
script: lein do clean, deps, compile, uberjar
deploy:
  provider: s3
  region: eu-central-1
  skip_cleanup: true
  bucket: "kite-notifier-lambda-build"
  acl: public_read
  local_dir: build
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
